# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

pod 'Masonry'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'ReactiveObjC'
pod 'TABAnimated'

#pod 'IQKeyboardManager'
#pod 'SSKeychain'
#pod 'JXCategoryView'
#pod 'JXPagingView/Pager'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'DZNEmptyDataSet'
#pod 'WZLBadge'

source 'https://github.com/CocoaPods/Specs.git'
target 'RACProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for RACProject

  target 'RACProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
